repo_name: fakenos/fakenos
repo_url: https://github.com/fakenos/fakenos
site_author: Denis Mulyalin
site_description: FakeNOS, Network, SSH
site_name: FakeNOS
site_url: https://fakenos.github.io/fakenos
docs_dir: docs/
theme:
  logo: assets/logo.svg
  favicon: assets/logo.svg
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - content.tabs.link
    - content.footnote.tooltips
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: brown
      accent: deep orange
    - scheme: default 
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: brown
      accent: deep orange
  language: en
extra:
  homepage: /overview/overview.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: "#"
  - footnotes
  - tables

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            heading_level: 3
            show_object_full_path: true
            show_signature_annotations: true
            docstring_section_style: list
            merge_init_into_class: true
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true
          nav_translations:
            Overview: Resumen
            Why?: ¿Por qué?
            What?: ¿Qué?
            How?: ¿Cómo?
            What not?: ¿Qué no?
            References: Referencias
            Examples: Ejemplos
            Script Development: Desarrollo de scripts
            Automatic testing - CI/CD: Pruebas automáticas - CI/CD
            Usage: Uso
            Installation: Instalación
            Getting Started: Empezar
            Inventory: Inventario
            Running in Docker Container: Ejecutar en contenedor Docker
            Platforms: Plataformas
            Development: Desarrollo
            Main: Principal
            Conventions: Convenciones
            Tasks: Tareas
            Creating a new platform: Crear una nueva plataforma
            Creating NOS Plugin: Crear un complemento NOS
            Github Actions: Acciones de Github
            Collaborators: Colaboradores
        - locale: ca
          name: Català
          build: true
          nav_translations:
            Overview: Resum
            Why?: Per què?
            What?: Què?
            How?: Com?
            What not?: Què no?
            References: Referències
            Examples: Exemples
            Script Development: Desenvolupament de scripts
            Automatic testing - CI/CD: Proves automàtiques - CI/CD
            Usage: Ús
            Installation: Instal·lació
            Getting Started: Començar
            Inventory: Inventario
            Running in Docker Container: Executar en contenidor Docker
            Platforms: Plataformes
            Development: Desenvolupament
            Main: Principal
            Conventions: Convencions
            Tasks: Tasques
            Creating a new platform: Crear una nova plataforma
            Creating NOS Plugin: Crear un complement NOS
            Github Actions: Accions de Github
            Collaborators: Col·laboradors


nav:
  - Overview:
    - Overview: index.md
    - Why?: overview/why.md
    - What?: overview/what.md
    - How?: overview/how.md
    - What not?: overview/what_not.md
    - References: overview/references.md
  - Examples:
    - Examples: examples.md
    - Script Development: examples/developing_scripts.md
    - Automatic testing - CI/CD: examples/automatic_testing.md
  - Usage:
    - Installation: usage/installation.md
    - Getting Started: usage/getting_started.md
    - Inventory: usage/fakenos_inventory.md
    - Running in Docker Container: usage/running_in_docker.md
  - Platforms: platforms.md
  - Development:
    - Main: development.md
    - Conventions: development/conventions.md
    - Tasks: development/tasks.md
    - Creating a new platform: development/creating_new_platforms.md
    - Creating NOS Plugin: development/creating_nos_plugin.md
    - Github Actions: development/github_actions.md
  - Collaborators:
    - Collaborators: collaborators.md
  - API:
    - Core API: api/core_api_reference.md
    - Built-in Plugins API: api/builtin_plugins_api_reference.md


